### ISSUE TITLE
Python Dependencies Needed

### ISSUE THREAD

**Issue by pythoninthegrass** [michael-yin/wagtail-bootstrap-blog#12]
Hi @michael-yin. Thanks for putting these tutorials together -- they've been a big help as I'm new to Django and Wagtail.

When running your blog locally, I ran into Python/pip dependencies that wasn't documented in your README.md.

1. Had to install `wheel` in the virtualenv (already present on the system):
```
git clone https://github.com/michael-yin/wagtail-bootstrap-blog.git
cd wagtail-bootstrap-blog/
python3 -m venv env
source env/bin/activate
pip3 install -r requirements.txt
```
Produces this output: [wagtail-bootstrap-blog-stdout.log](https://github.com/AccordBox/wagtail-bootstrap-blog/files/3737000/wagtail-bootstrap-blog-stdout.log)

To solve, within virtualenv, I ran `pip3 install wheel`, then `pip3 uninstall -r requirements.txt`.

2. On Ubuntu 19.04, I also [needed these packages](https://pillow.readthedocs.io/en/latest/installation.html) for Pillow:
```
sudo apt-get install -y python3-dev python3-setuptools # previously installed
sudo apt-get install -y libtiff5-dev libjpeg8-dev libopenjp2-7-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python-tk libharfbuzz-dev libfribidi-dev
```
Once the dependencies were fixed, `pip3 install -r requirements.txt && ./manage.py runserver` worked as expected.

Thought they might be good points to document for other users.

**Comment by michael-yin** [comment]
@pythoninthegrass 

The version 2 is now available and I will close this issue.

Thx.
