### ISSUE TITLE
wagtail search backends issue

### ISSUE THREAD

**Issue by eugenehiggins** [michael-yin/wagtail-bootstrap-blog#129]
I'm on chapter 4.9: Set Up the Site, and I was getting an error upon trying to add the BlogPage:
` raise InvalidSearchBackendError("Could not find backend '%s': %s" % (wagtail.search.backends.InvalidSearchBackendError: Could not find backend 'wagtail.search.backends.database':`

You go over the fix in chapter 11, but I'm getting the error in chapter 4. I found the answer here: https://docs.wagtail.org/en/v2.8.1/reference/contrib/postgres_search.html
I needed to change the `WAGTAILSEARCH_BACKENDS` value and add `'wagtail.contrib.postgres_search',` as an app in `INSTALLED_APPS`, among other things found on the above link. 

I recommend moving the steps in chapter 11.3 to before chapter 4 to avoid this error.

**Comment by kevinwen2018** [comment]
您好，邮件已收到，主人会尽快给您回复。

**Comment by michael-yin** [comment]
@eugenehiggins 

Thanks for your feedback, I will update my book in a bit.

Thx
