### ISSUE TITLE
django.core.urlresolvers outdated

### ISSUE THREAD

**Issue by sagayev** [michael-yin/wagtail-bootstrap-blog#14]
Hi Michael,

I got the 

> ImportError: No module named 'django.core.urlresolvers'

in **blog/templatetags/blogapp_tags.py** 

`from django.core.urlresolvers import resolve`
is not used within the code. 
FYI, Django 2.0 removes the `django.core.urlresolvers` module, which was moved to `django.urls` in version 1.10.

Source: [https://stackoverflow.com/questions/43139081/importerror-no-module-named-django-core-urlresolvers](url)

**Comment by michael-yin** [comment]
@sagayev 

The version 2 is now available and I will close this issue.

Thx.
