### ISSUE TITLE
el-pagination bug

### ISSUE THREAD

**Issue by WeeDom** [michael-yin/wagtail-bootstrap-blog#16]
Hi,

Great tutorial - I thought I'd try and help by showing you this that I found. It stopped me from doing the pagination piece.

```
System check identified no issues (0 silenced).
February 07, 2020 - 14:18:37
Django version 3.0.3, using settings 'weedoms_tut.settings.dev'

```
I ran `manage.py 0.0.0.0:8000` and got this error:
```
File "/usr/local/lib/python3.7/site-packages/el_pagination/models.py", line 8, in <module>
    from django.utils.encoding import iri_to_uri, python_2_unicode_compatible, force_text
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding' (/usr/local/lib/python3.7/site-packages/django/utils/encoding.py)
^Croot@835235c3d807:/app/weedoms_tut# pip install python_2_unicode_compatible
ERROR: Could not find a version that satisfies the requirement python_2_unicode_compatible (from versions: none)
ERROR: No matching distribution found for python_2_unicode_compatible
WARNING: You are using pip version 20.0.1; however, version 20.0.2 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
```
I did a LOT of digging around, then found this:

`https://github.com/shtalinberg/django-el-pagination/pull/137/commits/b10a2dc89d63b891345de7e0cb3a391e36ffd1ae` - it's a known bug.

and downloaded the repo

```
$ git branch -a --contains b10a2dc89d63b891345de7e0cb3a391e36ffd1ae
* develop
  remotes/origin/HEAD -> origin/develop
  remotes/origin/develop
```
just thought it might be worth you knowing.

**Comment by michael-yin** [comment]
@WeeDom 

Please use Django 2.x instead of Django3.x so this issue should be resolved.

Thx.

**Comment by WeeDom** [comment]
Hi, Michael,

That's not really an option for me as my employer is exclusively using the latest version. I'll just skip over the pagination bit.

Again, thanks for the tutorial - great work.

Thanks
WeeDom
