### ISSUE TITLE
Blog writeup: Add full snippet of STATICFILES_FINDER

### ISSUE THREAD

**Issue by PrithiPal** [michael-yin/wagtail-bootstrap-blog#21]
The issue is in regards to the blog post "How to use SCSS/SASS in your Django project (Python Way)" here: https://www.accordbox.com/blog/how-use-scss-sass-your-django-project-python-way/.

This is not an issue per se but a suggestion. I followed the tutorial to incorporate SCSS in my Django project locally (not Production). In your writeup, **I suggest you include the full snippet of ``` STATICFILES_FINDERS ```** such as 

``` 
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
)
```
instead of just "add compressor.finders.CompressorFinder" to ``` STATICFILES_FINDERS```

Probably this could be intuitive to you but not always for the reader. I never had the STATIC_FINDERS in my settings.py. Earlier I only had ``` compressor.finders.CompressorFinder ``` in ``` STATICFILES_FINDER ``` so my ``` collect static ``` did not export any changes in static files in my app. After including all three Finder in ```STATICFILES_FINDERS ```, it works fine.

**Comment by michael-yin** [comment]
@PrithiPal 

The version 2 is now available and I will close this issue.

Thx.
