### ISSUE TITLE
Error in code?

### ISSUE THREAD

**Issue by thexiaozhuzhu** [michael-yin/wagtail-bootstrap-blog#3]
Hi there, great tutorial!

I notice if you are following the online tutorial in this page
https://blog.michaelyin.info/2017/12/25/how-use-streamfield-wagtail/

it states in blocks.py
 class Meta:
        template = 'blog/blocks/block.html'

I think this should be column.html?
I just checked here and it is indeed column.html!
https://github.com/michael-yin/wagtail-bootstrap-blog/blob/master/blog/blocks.py

But if you are going thru the online tutorial it might be quite confusing.  Thanks!  Woof woof.

**Comment by michael-yin** [comment]
@thexiaozhuzhu 
Yes, the code in my blog have some mistake, I have added it in my todolist, and will fix it in this weekend
Thanks.
