### ISSUE TITLE
'Page' object has no attribute 'reverse_subpage' Error

### ISSUE THREAD

**Issue by thexiaozhuzhu** [michael-yin/wagtail-bootstrap-blog#4]
Hi there again, so the error I had earlier in the day was this mainly.  After trying quite a bit to troubleshoot, I decided to give up and restart by cloning your git and starting with a fresh new virtualenv.

However, I still get this same error.

It traces to anywhere such in the components folder such as sidebar.html, etc
<form role="search" method="get" class="form-search" action="{% routablepageurl blog_page "post_search" %}" method="get">

I tried with your version of wagtail in requirements folder such as 1.10.1 as well as the newer version.

**Comment by michael-yin** [comment]
I have pushed a lot of commits these days and some commits might not work as expected,

You can try commit 91656181e5990e4bd16bb58ae4a38f300ed0d363 using `git checkout`, I have confirmed that this commit work fine.

If you have any problem, please let me know

Thanks.
