### ISSUE TITLE
Wrong app name for routable page

### ISSUE THREAD

**Issue by krzysztofjeziorny** [michael-yin/wagtail-bootstrap-blog#83]
The [Routable Page](https://www.accordbox.com/blog/wagtail-tutorials-routable-page/) tutorial mentions including the `"wagtail.contrib.wagtailroutablepage",` app, which should be `"wagtail.contrib.routable_page",` as the [documentations](https://docs.wagtail.io/en/stable/reference/contrib/routablepage.html) says.

**Comment by michael-yin** [comment]
@krzysztofjeziorny 

Sorry, the content on my blog is a little outdated, the code in my eBook should work without issue.

Thx.
