### ISSUE TITLE
Waiting for PostgreSQL to become available...

### ISSUE THREAD

**Issue by scott-schafer** [michael-yin/wagtail-bootstrap-blog#90]
Hello,
I keep getting this message "Waiting for PostgreSQL to become available..." in my terminal after running ```docker-compose logs -f```. 
The full terminal output looks like this
```
$ docker-compose logs -f
Attaching to wagtail-bootstrap-blog_web_1, wagtail-bootstrap-blog_db_1
db_1   | 2021-03-10 21:31:50.754 UTC [1] LOG:  starting PostgreSQL 12.0 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit
db_1   | 2021-03-10 21:31:50.755 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1   | 2021-03-10 21:31:50.755 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1   | 2021-03-10 21:31:50.940 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1   | 2021-03-10 21:31:51.158 UTC [19] LOG:  database system was shut down at 2021-03-10 21:31:45 UTC
db_1   | 2021-03-10 21:31:51.193 UTC [1] LOG:  database system is ready to accept connections
db_1   | 2021-03-10 21:48:40.891 UTC [1] LOG:  received smart shutdown request
db_1   | 2021-03-10 21:48:40.944 UTC [1] LOG:  background worker "logical replication launcher" (PID 25) exited with exit code 1
db_1   | 2021-03-10 21:48:40.944 UTC [20] LOG:  shutting down
db_1   | 2021-03-10 21:48:41.106 UTC [1] LOG:  database system is shut down
db_1   | 2021-03-10 21:55:57.355 UTC [1] LOG:  starting PostgreSQL 12.0 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit
db_1   | 2021-03-10 21:55:57.355 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1   | 2021-03-10 21:55:57.355 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1   | 2021-03-10 21:55:57.480 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1   | 2021-03-10 21:55:57.723 UTC [20] LOG:  database system was shut down at 2021-03-10 21:48:41 UTC
db_1   | 2021-03-10 21:55:57.850 UTC [1] LOG:  database system is ready to accept connections
web_1  | Waiting for PostgreSQL to become available...
web_1  | Waiting for PostgreSQL to become available...
web_1  | Waiting for PostgreSQL to become available...
```
Not sure why I am getting this. I don't have any real experience with Docker but I'm up for anything. Any input would be great,
Thanks!

**Comment by michael-yin** [comment]
@scott-schafer 

1. Please check db login credential in the docker-compose.yml
2. Please check the login credential used by `web` service,  you can check `compose/local/web/entrypoint`

**Comment by scott-schafer** [comment]
Hi Michael,
I still can not get this to work, here is what I have for credentials, it all starts wit the ```~/.env/.dev-sample``` file. From there my docker-compose.yml looks like this,
```
    environment:
      - POSTGRES_DB=SQL_DATABASE
      - POSTGRES_USER=SQL_USER
      - POSTGRES_PASSWORD=SQL_PASSWORD
 ```
the entrypoint file looks like this
```
try:
    psycopg2.connect(
        dbname="${SQL_DATABASE}",
        user="${SQL_USER}",
        password="${SQL_PASSWORD}",
        host="${SQL_HOST}",
        port="${SQL_PORT}",
    )
```
and finally my base.py file looks like this,
```
DATABASES = {
    "default": {
        "ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("SQL_DATABASE", os.path.join(BASE_DIR, "db.sqlite3")),
        "USER": os.environ.get("SQL_USER", "user"),
        "PASSWORD": os.environ.get("SQL_PASSWORD", "password"),
        "HOST": os.environ.get("SQL_HOST", "localhost"),
        "PORT": os.environ.get("SQL_PORT", "5432"),

    }
}
```
I really hope that you see something out of place as I have spent a lot of time digging around to figure this out.
Thanks for your time,
Scott

**Comment by michael-yin** [comment]
@scott-schafer 

Please note `POSTGRES_DB`, `POSTGRES_USER ` and `POSTGRES_PASSWORD ` is used by db service.

The Django settings file is reading value from `SQL_ENGINE ` `SQL_DATABASE `

One simple solution is to set the value below to Django `DATABASES` directly, and this is simpler for you to understand.

```
SQL_DATABASE=wagtail_bootstrap_blog
SQL_USER=wagtail_bootstrap_blog
SQL_PASSWORD=wagtail_bootstrap_blog

SQL_ENGINE=django.db.backends.postgresql
SQL_HOST=db
SQL_PORT=5432
```

Thx.

**Comment by TalRodin** [comment]
I am getting the same error.

**Comment by scott-schafer** [comment]
Hi TalRodin,
The solution worked for me is that after making any changes to your .env, base.py or your docker-compose.yml files you will need to re-build your container run. `docker-compose build --no-cache` 
In my case I left the .env file and the base.py file alone and hard-coded the docker-compose.yml with: 
`
SQL_DATABASE=wagtail_bootstrap_blog
SQL_USER=wagtail_bootstrap_blog
SQL_PASSWORD=wagtail_bootstrap_blog
`
Hope this helps.

**Comment by TalRodin** [comment]
Hi, thank you Scott, 
But unfortunately it did not help.

**Comment by scott-schafer** [comment]
Hi TalRodin,
I pulled up Michael's latest tutorial and the setup in the dockerizing chapter looks fine.
```
#docker-compose.yml
...
db:
image: postgres:14.0-alpine
volumes:
- postgres_data:/var/lib/postgresql/data/
environment:
- POSTGRES_DB=wagtail_blog
- POSTGRES_USER=wagtail_blog
- POSTGRES_PASSWORD=wagtail_blog
volumes:
postgres_data:
```
The .env file
```
#.dev-sample

SQL_ENGINE=django.db.backends.postgresql
SQL_DATABASE=wagtail_blog
SQL_USER=wagtail_blog
SQL_PASSWORD=wagtail_blog
SQL_HOST=db
SQL_PORT=5432
```
And lastly the base.py file
```
#base.py

import os
DATABASES = {
    "default": {
        "ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("SQL_DATABASE", os.path.join(BASE_DIR, "db.sqlite3")),
        "USER": os.environ.get("SQL_USER", "user"),
        "PASSWORD": os.environ.get("SQL_PASSWORD", "password"),
        "HOST": os.environ.get("SQL_HOST", "localhost"),
        "PORT": os.environ.get("SQL_PORT", "5432"),
    }
}
```
In the base.py file make sure that the `import os` is towards the top of your base.py file.

In the tutorial Michael likes to run containers in `-d` detached mode, you can view all running container by using `docker-compose ps`. Which simple means they are always running on your computer and eating up your computers resources and depending what files you are working on can be problematic. 

I am thinking that you should remove all of your containers and the network. So `cd ` into your project directory and run `docker-compose down` this will stop the containers from running and remove the network. 

Next remove the containers either one at a time or you can use `docker container prune` this will remove all stopped containers on your computer, be careful that don't remove something that you don't want to remove like containers for an other project. If this is your first Docker project then `docker-compose prune` will be fine.

Once you have a clean starting point then run `docker-compose build` once that is complete run `docker-compose up` to start the containers. You can use `docker-compose stop` or `ctrl+c` to stop the containers. 

I don't run `-d` detached containers in local-development. 
`ctrl+c` and every container is stopped. 
`docker-compose up` and their all started up again.

In the beginning I had a lot of frustration with this as well but I must say the rewarding feeling when you get it working is just amazing! I use Docker all the time now, in my opinion it is the only way to build.

Good Luck!
